version: "3.9"

services:

  kafka:
    image: apache/kafka:3.7.0
    hostname: kafka
    networks:
      - telemetry-net

    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: ingress

    environment:
      CLUSTER_ID: "LTzrVJZ8RDiDoeDoQJbt7Q"

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka_data:/var/lib/kafka/data

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  kafka-init:
    image: apache/kafka:3.7.0
    networks:
      - telemetry-net
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo '--- Attente de Kafka ---'
        until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1; do
          echo 'Kafka pas encore prêt...'
          sleep 5
        done

        echo '--- Création du topic telemetry ---'
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists \
          --topic telemetry \
          --partitions 1 \
          --replication-factor 1 \
          --bootstrap-server kafka:9092

        echo '--- Création du topic alerts ---'
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists \
          --topic alerts \
          --partitions 1 \
          --replication-factor 1 \
          --bootstrap-server kafka:9092

        echo '--- Topics existants ---'
        /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server kafka:9092

        echo '--- INIT TERMINÉ ---'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10

  producer:
    image: mousse2025/producer:latest
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - telemetry-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  consumer:
    image: mousse2025/consumer:latest
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - telemetry-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  api:
    image: mousse2025/api:latest
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: ingress
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - telemetry-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  telemetry-net:
    driver: overlay
    attachable: true

volumes:
  kafka_data:
    driver: local