# kafka-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command:
        - sh
        - -c
        - |
          until nc -z kafka 9092; do
            echo "Attente de Kafka..."
            sleep 5
          done
          echo "Kafka est prêt."
      containers:
      - name: kafka-init
        image: apache/kafka:3.7.0
        command:
        - sh
        - -c
        - |
          /opt/kafka/bin/kafka-topics.sh --create --if-not-exists \
            --topic telemetry --partitions 1 --replication-factor 1 \
            --bootstrap-server kafka:9092
          /opt/kafka/bin/kafka-topics.sh --create --if-not-exists \
            --topic alerts --partitions 1 --replication-factor 1 \
            --bootstrap-server kafka:9092
          echo "Topics créés."