FROM python:3.10-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt
FROM python:3.10-slim
WORKDIR /app
RUN mkdir -p /home/appuser
COPY --from=builder /install /usr/local
COPY producer_car.py .
RUN chown -R 1000:1000 /app /home/appuser
USER 1000
ENTRYPOINT ["python", "producer_car.py"]
